# Normal Person Method

Below is the iterative way of solving eight queens problem. 

*Algorithm*<br>
Basically, it works like placing queen in the board one by one. If the queen didn't attack each others, then attempt to place a new queen. The code is implement with some level of recursion to make sure that all the trials is explored.

It takes more than 30 minutes to find out all the solutions

In [89]:
import numpy as np

class eightqueen: 
    def __init__(self):
        self.found = np.ones([8,8])
        self.counter = 0
        
    def run(self):
        board = np.zeros([8,8])
        self.place_queen(board)
    
    # Create a function to check the board
    def check_board(self, board):
        # Check for hori
        check_vert = np.max(np.sum(board, axis = 0))    

        # Check for vert
        check_hori = np.max(np.sum(board, axis = 1))
        if check_hori > 1 or check_vert >1:
            return False

        # Check for Diag 
        diag_sum = np.array([])
        for diag in range(2, 9):
            num_up = 0
            num_down = 0
            for i in range(diag):
                num_up += board[i][-diag + i]
                num_down += board[8-1-i][-8 + (diag- 1) - i ]
            diag_sum = np.append(diag_sum, num_up)
            if diag != 8:
                diag_sum = np.append(diag_sum, num_down)

        # Check for inv_diag 
        inv_diag_sum = np.array([])
        for inv_diag in range(2,9):
            num_up = 0
            num_down = 0
            for i in range(inv_diag):
                num_up += board[i][inv_diag - 1 - i]
                num_down += board[8-1-i][8 - (inv_diag) + i]
            inv_diag_sum = np.append(inv_diag_sum, num_up)
            if inv_diag != 8:
                inv_diag_sum = np.append(inv_diag_sum, num_down)

        if np.max(diag_sum) > 1 or np.max(inv_diag_sum) > 1:
            return False
        return True

    
    def check_found(self, board):
        if np.sum(np.all(board == self.found)) >= 1:
            return True
        else:
            return False

    def place_queen(self, board):
        # Create a function for brute force
        for i in range(0, 8):
            for j in range(0, 8):
                # If the board is found, then stopped
                if self.check_found(board):
                    print("Find")
                    return None

                # If the board has 8 queen, stop the current iteration
                if np.sum(board) == 8:
                    print('Found a way')
                    print(board)
                    self.found = np.stack((self.found, board))
                    return None

                # If the move is illegal, try other moves
                if board[i][j] == 1:
                    continue
                else:
                    board_next = board.copy()
                    board_next[i][j] = 1

                # If the new board is illegal, try next move
                if self.check_board(board_next) == False:
                    pass
                # If the move is legal, try out the remaining chance
                else:
                    print(self.counter)
                    self.counter +=1
                    self.place_queen(board_next)

# Recursive Version

Below is the Resurvie way of solving eight queens problem. 

*Algorithm*<br>
Basically, it 


In [128]:
import numpy as np

class eightqueenRecur: 
    def __init__(self):
        self.counter = 0
        
    def run(self):
        board = np.zeros([8,8])
        self.place_queen(board, 0)
    
    # Create a function to check the board
    def check_board(self, board):
        # Check for hori
        check_vert = np.max(np.sum(board, axis = 0))    

        # Check for vert
        check_hori = np.max(np.sum(board, axis = 1))
        if check_hori > 1 or check_vert >1:
            return False

        # Check for Diag 
        diag_sum = np.array([])
        for diag in range(2, 9):
            num_up = 0
            num_down = 0
            for i in range(diag):
                num_up += board[i][-diag + i]
                num_down += board[8-1-i][-8 + (diag- 1) - i ]
            diag_sum = np.append(diag_sum, num_up)
            if diag != 8:
                diag_sum = np.append(diag_sum, num_down)

        # Check for inv_diag 
        inv_diag_sum = np.array([])
        for inv_diag in range(2,9):
            num_up = 0
            num_down = 0
            for i in range(inv_diag):
                num_up += board[i][inv_diag - 1 - i]
                num_down += board[8-1-i][8 - (inv_diag) + i]
            inv_diag_sum = np.append(inv_diag_sum, num_up)
            if inv_diag != 8:
                inv_diag_sum = np.append(inv_diag_sum, num_down)

        if np.max(diag_sum) > 1 or np.max(inv_diag_sum) > 1:
            return False
        return True

    def place_queen(self, board, line):
        # Create a function for brute force
        for i in range(0, 8):
            # If the board has 8 queen, stop the current iteration
            if np.sum(board) == 8:
                self.counter += 1
                print('Found a way')
                print(board)
                return None

            # If the move is illegal, try other moves
            if board[line][i] == 1:
                continue
            else:
                board_next = board.copy()
                board_next[line][i] = 1

            # If the new board is illegal, try next move
            if self.check_board(board_next) == False:
                pass
            # If the move is legal, try out the remaining chance
            else:
                self.place_queen(board_next, line + 1)
                
    def get_counter(self):
        return self.counter

In [129]:
test = eightqueenRecur()
test.run()

Found a way
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
Found a way
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
Found a way
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
Found a way
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
Found a way
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1

Found a way
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
Found a way
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]
Found a way
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
Found a way
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]
Found a way
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0

In [130]:
test.get_counter()

92